apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: apple.vbvit@gmail.com
    privateKeySecretRef:
      name: letsencrypt-issuer-key
    solvers:
    - http01:
        ingress:
          class: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
spec:
  secretName: my-https-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: "first.wdb.com.ua"
  dnsNames:
  - "first.wdb.com.ua"
