apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: first-app
  jwtRules:
  - issuer: "http://jwks-svc-cluster"
    jwks: |
      {
        "keys": [
          {
            "e": "AQAB",
            "kty": "RSA",
            "n": "1wdfNL86K54Y7Vp9yb66hrN88RzYMogqAUblTJSMZEypy3jbDP1ctk4TqMdpiba0ovKbyVZUfLl62HUdB1HfeKlI-lEiH090Yyi1LbxdvAP5gcRQos0Nn3DWQSi5Z1Mh506G1q8NKCd8OhceosuM2PuK25UXe-gparBip1sxYh4OgZUDKZF3qnzK3LVeGh76qJB-G1G1iIwPI_E65rosV5YDWx6dfI2SbqYMmjfdeLLSUInsIFMohBoh8-nNIh5Jj-D0v2jiLnRb7Al15VmrY8MHg5R_nsBoKWUn3z9Lsd_4bkuGCYNSGbAKV_ITgvc-IN3rySkGTn4gkBa4AEGWLQ",
            "kid": "Y43RTBdYXWfJD0HlcsT5OOOd9IDJAAzBRqJxncL6SLI"
          }
        ]
      }
