apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: first-app
  jwtRules:
  - issuer: "http://jwks-svc-cluster"
    jwksUri: "http://second.wdb.com.ua/.well-known/jwks.json"
