apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: first-deployment
  name: first-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
        version: "24.4.0.1"
    spec:
      containers:
        - name: web-first
          image: vbvit/http2-server:0.2
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
