apiVersion: v1
kind: Service
metadata:
  name: argocd-svc-node
  namespace: argocd
spec:
  ports:
  - name: http
    nodePort: 30100
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort

