apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-1
  namespace: metallb-system
spec:
  addresses:
  - 172.16.100.105-172.16.100.119
  autoAssign: true
  avoidBuggyIPs: false

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement-1
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool-1
